### PR TITLE
dockerize stem skeleton

### PR DESCRIPTION
**Pull request by multi**
to start: exec `docker-compose up` in the project folder :)

### CODE REVIEW

**Comment by multi** [comment]
there is one caveat (at least on my side, docker machine is with virtualbox engine, and there is no inotify fs events propagation to client fs, so in order watchify to work - polling should be used) don't know that should be needed or not if the host os is linux ...

and one more thing

// from dna/_development/angel/build/css
watchy usage is not ok, it shouldn't be per file, should be only one process

// from dna/_development/angel/build/js
watchify per file also eats a lot of cpu :)

**Comment by outbounder** [comment]
@multi 

> watchy & watchify

We don't use them at least not in v0.1.0 ? 

I'll test the PR and let you know later what's the outcome. Can you provide any pre-requirements or steps which I need to do before doing `docker-compose up` like what version of docker to install & etc?

**Comment by multi** [comment]
@outbounder 

> We don't use them at least not in v0.1.0 ?

yeah, that's from another old repo, just wanted to note about that

there a no special pre-requirements, just install latest version of docker toolkit (which will give you docker, docker-machine, docker-compose, etc.)

**Comment by outbounder** [comment]
@multi docker toolkit or docker toolbox I need to install?

Because [docker toolbox](https://www.docker.com/docker-toolbox) seems as not supported for linux :question:

**Comment by multi** [comment]
You will need to follow this guide https://docs.docker.com/linux/

Sorry for the confusion, indeed docker toolkit is only for osx and windows...

**Comment by multi** [comment]
@outbounder PR updated :)

**Comment by outbounder** [comment]
@multi 

I got `docker-compose` and everything went well ok with it just after a good amount of downloading :)

Also converted your PR to `stack upgrade` here in `docker-upgrade` [branch](https://github.com/outbounder/organic-stem-skeleton/compare/docker-upgrade)

However when running `docker-compose up` I get this:

```
Cannot start container 8083fde4bd936a13368b28f0d2563d131e55f48559e5ee2f4442a87d78ce4171: [8] System error: exec: "docker/entrypoint.sh": permission denied
```

tried to naively fix that via change in `docker/Dockerfile.nodejs` but failed :thought_balloon: 

That said, I'm having focus on other parts and would like your input what should I do? (or even better new PR towards `docker-upgrade` branch :P )

**Comment by outbounder** [comment]
@multi a little note about testing your stack upgrade:

```
$ cd stem-skeleton-repo-folder
$ node ./node_modules/.bin/angel stack use docker-compose
... test, ie $ docker-compose up & etc
```

ie commit only `/upgrades/docker`  and reset your repo-folder to its upstream state to repeat testing :)

We have a prototype version of automated testing here https://github.com/outbounder/organic-stem-skeleton-tests however it is too early to mark it as usable, thus the above manual routine. Of course if you want - adapt it to your needs ;)

**Comment by multi** [comment]
@outbounder okay, will work & update this branch `docker-upgrade` :)
closing this PR

**Pull request closed without merging**
